site_name: example-project
repo_url: https://github.com/fpgmaas/example-project
site_url: https://fpgmaas.github.io/example-project
site_description: This is a template repository for Python projects that use Poetry for their dependency management.
site_author: Florian Maas

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
copyright: Maintained by Florian Maas.
theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: white
    accent: blue
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true